{"name": "Тест если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Передаем несуществующий логин, пароль проверяем код 404 и что телоответа содержит \"Недостаточно данных для входа\"", "parameters": [{"name": "login", "value": "'SashaKurochkin'"}, {"name": "password", "value": "'password1234'"}], "start": 1709910513310, "stop": 1709910513587, "uuid": "73da9d7a-462b-4e92-9d85-fd46932d371d", "historyId": "92cc7f4461bcf8a86f140f698738aa0a", "testCaseId": "13b58fa1aaf6b382c386cbb5e82acef8", "fullName": "tests.test_login_couriers.TestLoginCouriers#test_authentication_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_couriers"}, {"name": "subSuite", "value": "TestLoginCouriers"}, {"name": "host", "value": "LAPTOP-4KULGNVQ"}, {"name": "thread", "value": "10584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_couriers"}]}